spring.application.name=MesaLista

# URL de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/mesalista_db

server.address=10.10.10.10
server.port=9090
server.servlet.context-path=/mesalista

# CAMBIAR A TUS CREDENCIALES PARA QUE FUNCIONE
spring.datasource.username=root
spring.datasource.password=acore

# Para poder enviar a BackupConfig y hacer recursiva la validacion de credenciales al exportar Script SQL
backup.mysql.user=root
backup.mysql.password=acore
backup.mysql.database=mesalista_db

# Configuracion de JPA y Hibernatea
#spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL generadas por Hibernate
# spring.jpa.show-sql=true

# Formatear las consultas SQL para mayor legibilidad
spring.jpa.properties.hibernate.format_sql=true

# Nivel de logging de Hibernate
# logging.level.org.hibernate=DEBUG

# Dialecto de Hibernate para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

